msv:
  name: api-gateway-prod
server:
  port: 8090
spring:
  banner:
    location: classpath:banner/banner-prod.txt
  # customer
  cloud:
    gateway:
      routes:
        - id: msv-customer
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/customers/**
  #logging:
  #  level:
  #    org.springframework.cloud.gateway: DEBUG
  #    reactor.netty.http.client: DEBUG
  #    org.springframework.web: DEBUG
eureka:
  server:
    port: 8761
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    instance-id: ${msv.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}
logging:
  level:
    root: WARN