msv:
  api-gateway:
    property: api-gateway-dev
server:
  port: 8090
spring:
  banner:
    location: classpath:banner/banner-dev.txt
  # customer
  cloud:
    gateway:
      routes:
        - id: msv-customer
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/customers/**
  #logging:
  #  level:
  #    org.springframework.cloud.gateway: DEBUG
  #    reactor.netty.http.client: DEBUG
  #    org.springframework.web: DEBUG
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
logging:
  level:
    root: WARN