server:
  port: 8090
security:
  private-paths: # Rutas privadas para APIS (con JWT)
    - route: customer-service # Identificador del msv o api
      path: /api/v1/customers/** # Url donde resuelve el API
      url: lb://msv-customer-lb # Nombre del servicio registrado en Eureka Server
    - route: student
      path: /api/v1/students/**
      url: lb://student-lb
  public-paths: # Rutas públicas para APIS (sin JWT)
    - /api/v1/customers/**
    - /api/v1/students/**
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /webjars/**
    - /index.html
    - /swagger-resources/**
    - /favicon.ico
    - /auth/**
    - /login
    - /register
spring:
  application:
    name: api-gateway
  cloud:
#    loadbalancer:
#      cache:
#        enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
        primaryName: API Gateway
  show-actuator: true
logging:
  level:
    # root: WARN
    org.springframework.cloud.gateway: DEBUG
    api.azure.apigateway: DEBUG
    org.springframework.security: DEBUG