server:
  port: 8090
spring:
  application:
    name: api-gateway
  banner:
    location: classpath:banner/banner-prod.txt
  # customer
  cloud:
    gateway:
      routes:
        - id: msv-customer-CustomerController
          # uri: http://localhost:9010
          # "msv-customer-lb" is name instance-id: ${spring.application.name} of microservice customer - line 5
          uri: lb://msv-customer-lb
          predicates:
            - Path=/api/v1/customers/**
        - id: msv-customer-TestController
          uri: lb://msv-customer-lb
          predicates:
            - Path=/api/v1/test/**
        - id: msv-wikimedia-WikimediaController
          uri: lb://msv-wikimedia-produce-lb
          predicates:
            - Path=/api/v1/wikimedia/**
#  logging:
#    level:
#      org.springframework.cloud.gateway: DEBUG
#      reactor.netty.http.client: DEBUG
#      org.springframework.web: DEBUG
eureka:
#  server:
#    port: 8761
  instance:
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
#    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}
logging:
  level:
    root: WARN