msv:
  discovery-service:
    property: discovery-service-prod
server:
  port: 8761
spring:
  application:
    name: discovery-service
#eureka:
#  instance:
#    hostname: localhost  # Nombre del host para el Discovery Server
#    prefer-ip-address: true  # O false, si prefieres que utilice el nombre de host
#  client:
#    register-with-eureka: false
#    fetch-registry: false