msv:
  customer:
    property: msv-customer-dev
server:
  port: 0
spring:
  banner:
    location: classpath:banner/banner-dev.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank-dev
    username: banking
    password: banking123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  instance:
    instance-id: ${msv.customer.property}:${random.uuid}
logging:
  level:
    root: WARN
    #root: DEBUG