server:
  # port: 0 for management eureka multi instance
  port: 0
spring:
  application:
    name: msv-customer-lb
  banner:
    location: classpath:banner/banner-prod.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: banking
    password: banking123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
#  server:
#    port: 8761
  instance:
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
#    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}
logging:
  level:
    root: WARN
