server:
  port: 8082
spring:
  application:
    name: student
  banner:
    location: classpath:banner/banner-${SPRING_PROFILES_ACTIVE}.txt
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://localhost:8888}
    vault:
      enabled: true
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: http
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
      kv:
        enabled: true
        backend: secret
  output:
    ansi:
      enabled: ALWAYS
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true
    path: /v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      environment: ${SPRING_PROFILES_ACTIVE:dev}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
openapi:
  info:
    title: Student API - Dev
    github:
      url: https://github.com/josephmn/student.git
      definition: https://github.com/josephmn/student/blob/main/src/main/resources/openapi.yaml
    terms: http://swagger.io/terms/
    contact:
      name: Joseph Magallanes
      email: josephcarlos.jcmn@gmail.com
      url: https://www.linkedin.com/in/joseph-magallanes-nolazco/
    servers:
      url: http://localhost:${server.port}
      description: Local server Swagger
logging:
  level:
    root: INFO